# Custom Language File for Launcher Customizer

[ejs.app]
title = "Altis-Of-Life"

[ejs.landing]
mediaGitHubURL = "https://github.com/AltisOfLife/HeliosLauncher"
mediaXURL = "https://x.com/AltisOfLife"
mediaInstagramURL = "https://www.instagram.com/altisoflife/"
mediaYouTubeURL = "https://www.youtube.com/@altis-of-life-officiel7927"
mediaDiscordURL = "https://discord.gg/altisoflife"

[ejs.settings]
sourceGithubLink = "https://github.com/AltisOfLife/HeliosLauncher"
supportLink = "https://github.com/AltisOfLife/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Altis-Of-Life"
welcomeDescription = "Altis-Of-Life, c'est plus de douze ans d'existence à travers trois versions. Ce serveur RolePlay, basé sur Minecraft 1.7.10 et enrichi de nombreux mods, transforme votre expérience de jeu en y ajoutant des éléments inédits au gameplay."
welcomeDescCTA = "Vous n'êtes qu'à quelques clics d'Altis-Of-Life."
