[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "MOJANG STATUS"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essential"
newsButton = "NEWS"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez patienter.."
newsNavigationStatus = "{currentPage} of {totalPages}"
newsErrorLoadSpan = "Vérification de l'actualité.."
newsErrorFailedSpan = "Échec du chargement des nouvelles"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Pas d'actualités"

[ejs.login]
loginCancelText = "Cancel"
loginSubheader = "MINECRAFT LOGIN"
loginEmailError = "* Valeur non valide"
loginEmailPlaceholder = "EMAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Exigée"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "Vous vous souvenez de moi ?"
loginButtonText = "CONNEXION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à mojang et n'est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Se connecter avec Microsoft"
loginWithMojang = "Se connecter avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Available Servers"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "A propos"
navUpdates = "Mises à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajouter de nouveaux comptes ou gérer les comptes existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Minecraft Paramètres"
minecraftTabHeaderDesc = "Options relatives au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Se connecter automatiquement au serveur au démarrage."
launchDetachedTitle = "Lancer le processus du jeu indépendamment du lanceur."
launchDetachedDesc = "Si le jeu n'est pas détaché, la fermeture du lanceur entraînera également la fermeture du jeu."
tabModsHeaderText = "Paramètres des mods"
tabModsHeaderDesc = "Enable or disable mods."
switchServerButton = "Activer ou désactiver les mods."
requiredMods = "Mods requises"
optionalMods = "Mods optionnels"
dropinMods = "Mods à insérer"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Activez ou désactivez les shaders. Veuillez noter que les shaders ne fonctionneront correctement que sur des configurations puissantes. Vous pouvez ajouter des packs personnalisés ici."
selectShaderpack = "Sélectionner le pack de shaders"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérer la configuration Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "Maximum RAM"
minRAM = "Minimum RAM"
memoryDesc = "La mémoire vive minimale recommandée est de 5 gigaoctets. Le fait de définir les valeurs minimale et maximale sur la même valeur peut réduire le décalage."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner l'exécutable Java"
javaExecSelButtonText = "Choisissez un fichier"
javaExecDesc = "L'exécutable Java est validé avant le lancement du jeu.."
javaPathDesc = "Le chemin devrait se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Options à fournir à la JVM lors de l'exécution. <em>-Xms</em> et <em>-Xmx</em> ne doit pas être inclus."
launcherTabHeaderText = "Paramètres du launcher"
launcherTabHeaderDesc = "Options liées au launcher."
allowPrereleaseTitle = "Autoriser les mises à jour avant leur sortie."
allowPrereleaseDesc = "Les préversions comprennent de nouvelles fonctionnalités qui n'ont peut-être pas été entièrement testées ou intégrées. Cela sera toujours le cas si vous utilisez une préversion."
dataDirectoryTitle = "Répertoire de données"
selectDataDirectory = "Sélectionner le répertoire de données"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers du jeu et les installations Java locales seront stockés dans le répertoire de données.<br>Les captures d'écran et les sauvegardes mondiales sont stockées dans le dossier d'instance correspondant à la configuration du serveur."
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Consulter les informations et les notes de mise à jour pour la version actuelle."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "DevTools Console"
releaseNotes = "Release Notes"
changelog = "Changelog"
noReleaseNotes = "Aucune note de mise à jour"
viewReleaseNotes = "Consulter les notes de mise à jour sur GitHub"
launcherUpdatesHeaderText = "Launcher Mises à jour"
launcherUpdatesHeaderDesc = "Téléchargez, installez et consultez les mises à jour pour le launcher."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Nouveautés"
updateReleaseNotes = "Notes de mise à jour"

[ejs.waiting]
waitingText = "En attendant Microsoft.."

[ejs.welcome]
continueButton = "CONTINUER"


[js.discord]
waiting = "En attente du client.."
state = "Serveur: {shortId}"

[js.index]
microsoftLoginTitle = "Microsoft Connexion"
microsoftLogoutTitle = "Microsoft Déconnexion"

[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION"
success = "SUCCÈS"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur non valide"
requiredValue = "* Obligatoire"

[js.login.error.unknown]
title = "Erreur inconnue lors de la connexion"
desc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter.."
failureTitle = "Erreur lors du lancement"
failureText = "Pour plus de détails, consultez la console (CTRL + Maj + i)."
okay = "D'accord"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement.."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Vérification des informations système..."
noCompatibleJava = "Non compatible<br>Installation Java trouvée"
installJavaMessage = "Pour lancer Minecraft, vous devez disposer d'une installation 64 bits de Java {major}. Souhaitez-vous que nous en installions une copie ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement Java..."
javaDownloadFailureTitle = "Erreur lors du téléchargement de Java"
javaDownloadFailureText = "Pour plus de détails, consultez la console (CTRL + Maj + i)."
javaRequired = "Java est requis<br>pour lancer le launcher"
javaRequiredMessage = 'Une installation x64 valide de Java {major} est nécessaire pour démarrer.<br><br>Veuillez vous référer à notre <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Guide de gestion Java</a> pour obtenir des instructions sur l'installation manuelle de Java.'
javaRequiredDismiss = "Je comprends"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Impossible de trouver la distribution OpenJDK."
javaDownloadCorruptedError = "Le JDK téléchargé a un hachage incorrect, le fichier est peut-être corrompu."
extractingJava = "Extraction Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des informations du serveur.."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger une copie de l'index de distribution. Consultez la console (CTRL + Maj + i) pour plus de détails."
pleaseWait = "Veuillez patienter..."
errorDuringLaunchTitle = "Erreur lors du lancement"
seeConsoleForDetails = "Pour plus de détails, consultez la console (CTRL + Maj + i)."
validatingFileIntegrity = "Vérification de l'intégrité du fichier..."
errorDuringFileVerificationTitle = "Erreur lors de la vérification du fichier"
downloadingFiles = "Téléchargement des fichiers..."
errorDuringFileDownloadTitle = "Erreur lors du téléchargement du fichier"
preparingToLaunch = "Préparation au lancement..."
launchingGame = "Lancement du jeu..."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, n'a pas pu être téléchargé correctement. Par conséquent, le jeu ne peut pas être lancé.<br><br>Pour résoudre ce problème, désactivez temporairement votre logiciel antivirus et relancez le jeu.<br><br>Si vous avez le temps, <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">signaler le problème</a> et nous indiquer quel logiciel antivirus vous utilisez. Nous les contacterons pour tenter de régler le problème."
doneEnjoyServer = "C'est fait. Profitez bien du serveur !"
checkConsoleForDetails = "Veuillez consulter la console (CTRL + Maj + i) pour plus de détails."

[js.landing.news]
checking = "Vérification des actualités"

[js.landing.discord]
loading = "Chargement du jeu..."
joining = "En route pour Altis-Of-Life !"
joined = "Explore Altis-Of-Life!"

[js.overlay]
dismiss = "Rejeter"

[js.settings.fileSelectors]
executables = "Executables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Une erreur s'est produite"
errorMessage = "Échec de l'authentification Microsoft. Veuillez réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Une erreur s'est produite"
errorMessage = "Échec de l'authentification Microsoft. Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionner un compte"
selectedButton = "Compte sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Avertissement<br>Ceci est votre dernier compte."
lastAccountWarningMessage = "Pour utiliser le lanceur, vous devez être connecté à au moins un compte. Vous devrez vous reconnecter après.<br><br>Êtes-vous sûr de vouloir vous déconnecter ?"
confirmButton = "J'en suis sûr"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Sélectionner un compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Déconnexion"

[js.settings.dropinMods]
removeButton = "Supprimer"
deleteFailedTitle = "Échec de la suppression<br>Mod Drop-in {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n'est pas en cours d'utilisation et réessayez."
failedToggleTitle = "Échec de la commutation<br>Un ou plusieurs mods Drop-in"
okButton = "Okay"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Sélectionné: Java {version} ({vendor})"
invalidSelection = "Sélection non valide"
requiresJava = "Nécessite Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pre-release"
stableReleaseTitle = "Stable Release"
releaseNotesFailed = "Échec du chargement des notes de mise à jour."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle préversion disponible"
downloadingButton = "Téléchargement.."
downloadButton = 'Télécharger depuis GitHub <span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermez le launcher et exécutez le fichier dmg pour effectuer la mise à jour..</span>'
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Recherche de mises à jour.."

[js.settings.msftLogin]
errorTitle = "Échec de la connexion Microsoft"
errorMessage = "Nous n'avons pas pu authentifier votre compte Microsoft. Veuillez réessayer."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale: Impossible de charger l'index de distribution"
fatalErrorMessage = "Impossible d'établir une connexion avec nos serveurs pour télécharger l'index de distribution. Aucune copie locale n'était disponible pour le chargement. <br><br>L'index de distribution est un fichier essentiel qui fournit les dernières informations sur le serveur. Le launcher ne peut pas démarrer sans lui. Assurez-vous d'être connecté à Internet et relancez l'application."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec de l'actualisation de la connexion"
failedMessage = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez sélectionner un autre compte ou vous reconnecter."
failedMessageSelectAnotherAccount = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez vous reconnecter."
loginButton = "Connexion"
selectAnotherAccountButton = "Sélectionner un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Recherche de mises à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Vérifier les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur lors de la connexion :<br>Profil non configuré"
noProfileDesc = "Votre compte Microsoft ne dispose pas encore d'un profil Minecraft. Si vous avez récemment acheté le jeu ou l'avez obtenu via Xbox Game Pass, vous devez configurer votre profil sur <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si vous n'avez pas encore acheté le jeu, vous pouvez également le faire sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erreur lors de la connexion :<br>Pas de compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft n'est associé à aucun compte Xbox."
xblBannedTitle = "Erreur lors de la connexion :<br>Xbox Live indisponible"
xblBannedDesc = "Votre compte Microsoft provient d'un pays où Xbox Live n'est pas disponible ou est interdit."
under18Title = "Erreur lors de la connexion :<br>Autorisation parentale requise"
under18Desc = "Les comptes des utilisateurs âgés de moins de 18 ans doivent être ajoutés à une famille par un adulte."
unknownTitle = "Erreur inconnue lors de la connexion"
unknownDesc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne :<br>Méthode non autorisée"
methodNotAllowedDesc = "Méthode non autorisée. Veuillez signaler cette erreur."
notFoundTitle = "Erreur interne :<br>Introuvable"
notFoundDesc = "Le point de terminaison d'authentification est introuvable. Veuillez signaler ce problème."
accountMigratedTitle = "Erreur lors de la connexion :<br>Compte migré"
accountMigratedDesc = "Vous avez essayé de vous connecter avec un compte migré. Réessayez en utilisant l'adresse e-mail du compte comme nom d'utilisateur."
invalidCredentialsTitle = "Erreur lors de la connexion :<br>Identifiants non valides"
invalidCredentialsDesc = "L'adresse e-mail ou le mot de passe que vous avez saisi est incorrect. Veuillez réessayer."
tooManyAttemptsTitle = "Erreur lors de la connexion :<br>Trop de tentatives"
tooManyAttemptsDesc = "Il y a eu trop de tentatives de connexion avec ce compte récemment. Veuillez réessayer plus tard."
invalidTokenTitle = "Erreur lors de la connexion :<br>Token non valide"
invalidTokenDesc = "Le token d'accès fourni n'est pas valide."
tokenHasProfileTitle = "Erreur lors de la connexion :<br>Le token a un profil"
tokenHasProfileDesc = "Le token d'accès dispose déjà d'un profil attribué. La sélection des profils n'est pas encore implémentée."
credentialsMissingTitle = "Erreur lors de la connexion :<br>Identifiants manquants"
credentialsMissingDesc = "Le nom d'utilisateur/mot de passe n'a pas été saisi ou le mot de passe comporte moins de 3 caractères."
invalidSaltVersionTitle = "Erreur lors de la connexion :<br>Version Salt non valide"
invalidSaltVersionDesc = "Version de Salt non valide."
unsupportedMediaTypeTitle = "Erreur interne :<br>Type de média non pris en charge"
unsupportedMediaTypeDesc = "Type de média non pris en charge. Veuillez signaler cette erreur."
accountGoneTitle = "Erreur lors de la connexion :<br>Compte migré"
accountGoneDesc = "Le compte a été transféré vers un compte Microsoft. Veuillez vous connecter avec Microsoft."
unreachableTitle = "Erreur lors de la connexion :<br>Inaccessible"
unreachableDesc = "Impossible d'atteindre les serveurs d'authentification. Assurez-vous qu'ils sont en ligne et que vous êtes connecté à Internet.."
gameNotPurchasedTitle = "Erreur lors de la connexion :<br>Jeu non acheté"
gameNotPurchasedDesc = "Le compte avec lequel vous essayez de vous connecter n'a pas acheté de copie de Minecraft. Vous pouvez acheter un exemplaire sur <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Erreur inconnue lors de la connexion"
unknownErrorDesc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."
